# Adding OpenStreetMap vectors

One useful way to add existing vector information to a map, while also making it possible to customize its appearance, is to download data from OpenStreetMap (OSM). The process will be to download the OSM file for a given area, then open it, choose the layers that you want, filter these layers according to feature type, and then modify appearances.

## Downloading OSM data 

Start with some raster base map that lets you navigate to a place of interest (OSM map tiles, an orthophoto etc.). Zoom in to a small area, such as a neighborhood or several city blocks. Now select <kbd>Vector &rarr; OpenStreetMap &rarr; Download Data...</kbd>. In the window that appears, select <kbd>From map canvas</kbd> for the extent. (This is a simple way of defining the boundaries of the data you will download. Note that selecting large boundaries will result in very large file sizes.) Now click the <kbd>...</kbd> button next to <kbd>Output file</kbd> and select a file name and destination directory to which you will save the downloaded information.

## Opening the OSM file and selecting layers 

To add the OSM data you just downloaded, select <kbd>Layer &rarr; Add Layer &rarr; Add Vector Layer...</kbd>. Browse to the OSM file you just downloaded and select <kbd>OK</kbd> then <kbd>Open</kbd> to open it. You will now see a new window with a list of layers that this file contains. You can select some or all of these. When you hit <knd>OK</knd> you will see each of these layers appear on your map and in your <kbd>Layers Panel</kbd>. For the rest of this exercise, focus just on the lines layer.

## Labeling the vector data 

You can add labels to this new layer just as you did above. You may find, however, that there is too much information and that you want to filter it somehow. You can filter the labels themselves using the labels tab. Or you can filter the features in the layer as follows:

## Filtering the vector data 

To filter a layer, open the <kbd>Properties</kbd> window (right click the layer and select this) and go to the <kbd>General</kbd> tab. Scroll down and you will see a <kbd>Provider feature filter</kbd> box. Click on the <kbd>Query Builder</kbd> button just below this box on the right. This will bring up a new window in which you can write a query to filter the features in this layer according to their attribute fields. To do this, you need to know something about what these fields contain, and you can see this by clicking on a field and hitting the <kbd>Sample</kbd> button. You can then create a filter by double clicking on a field name, clicking an operator, and then double clicking a value. You will see the query being built as you do this in the box at the bottom. For example <kbd>"highway"='tertiary'</kbd> would filter the features to include only those for which the "highway" field has the value (character string in this case) 'tertiary'.

Another way of filtering, which is often easier, is to start by coloring the features according to some field of interest. In the <kbd>Style</kbd> tab, select <kbd>Categorized</kbd> in the selector at the top. Then choose the field you want to use for this in the <kbd>Column</kbd> selector. Hit the <kbd>Classify</kbd> button and QGIS will assign a different random color to each different value that appears in this field. Click <kbd>OK</kbd> to see how this looks on the map. You can now click the field in the <kbd>Layers Panel</kbd> to expand it to show each unique value and the color assigned to it. You can click any of these to remove or return it to the map.
