# Mapping Basics

## Mapping crime locations

### Obtaining Data

To get started, we will use data on reported assaults in New York City during November and December 2016. This has already been extracted from the <a href="https://data.cityofnewyork.us/">NYC Open Data</a> <a href="https://maps.nyc.gov/crime/">Crime Map</a> and can be downloaded simply by clicking the link below. Save it to a location where you will be able to find it again.

<a href="data/NYPD_Complaint_Map__Year_to_Date.csv">Download the Data</a>

### Adding data to your map

Add the data to your map using <kbd>Layer &rarr; Add Layer &rarr; Add Delimited Text Layer...</kbd> (same in both versions 2.18 and 3.4, although the item appears in a different position within the <kbd>Add Layer</kbd> choices in each).

Select the data file you want (for this exercise, use the file you just downloaded and saved: <samp>NYPD_Complaint_Map__Year_to_Date.csv</samp>). In the <kbd>Geometry definition</kbd>box, make sure <kbd>Point coordinates</kbd> is selected. Make sure that the <kbd>X field</kbd> and <kbd>Y field</kbd> boxes contain the correct field names from your data for the x and y coordinates. (In version 3.4 you need to first expand the <kbd>Geometry Definition</kbd> section.) You can check this by looking at the data preview shown in the bottom of the window. (In version 3.4 this is labeled <kbd>Sample Data</kbd>.) In this case, QGIS automatically recognizes that there are fields labeled Longitude and Latitude and that these should be x and y, respectively. Now click <kbd>OK</kbd>.

A new window will now pop up for you to select a Coordinate Reference System (CRS) for the layer you are adding. This will often require some thinking because selecting the wrong CRS will lead to your layer being incorrectly placed on the map (or sometimes not visible at all). For points recorded as Latitude and Longitude, you will want to use WGS 84 - EPSG 4326. (If you type 4326 in the filter bar at the top it will come up.) To view your new layer, you will probably need to pan and zoom to get to the location where it actually has data - in this case New York City. You can do that quickly by right-clicking on the layer in the Layers Panel and selecting <kbd>Zoom to Layer</kbd>. You may also need to make sure that the layer is not being covered by another layer. The order of the layers in the Layers Panel is the order in which they appear on the map (imagine actual layers of paper or transparent paper with features on a physical map). You can drag layers up and down in that list to change the order. To learn more about each point marked on the map, select <kbd>View &rarr; Identify Features</kbd> and click on a point. You will see information in the Identify Results panel on the right (although you may need to expand that panel to see the values associated with each feature.


## Printing or Exporting a Map

What you see in the QGIS console is useful for creating, modifying, and analyzing your map. If you want to share your map with someone or publish it as part of a report, you will want to use the print composer to produce high-quality output.

### Setting up the Print Composer

Select <kbd>Project &rarr; New Print Composer</kbd>. In the dialog box that pops up, you can give this print composer a title or leave the box blank and click OK for the default title. You will now see a new window with a canvas that you can use to compose exactly how you want your map to look.

### Adding a map

The most obvious thing you will want on your composed map is the map itself. Select <kbd>Layout &rarr; Add Map</kbd> and then use the mouse to draw a rectangle on the canvas where you want the map to appear. Notice that the map that will now appear in that box is essentially a mirror image of the map you currently have in the main console (although the dimensions may be different depending on how you draw the box). After drawing the box, you can still move it around using the <kbd>Layout &rarr; Move Item</kbd> tool, and you can move the map around within it using the <kbd>Layout &rarr; Move Content</kbd> tool. Notice that you can add more than one map to your canvas. This makes it possible to include inset maps, for example, showing where your detailed map lies at a larger scale.

### Adding a scale bar

You may wish to add a scale bar to your map, and you can do this easily using <kbd>Layout &rarr; Add Scalebar</kbd>. Again, you will need to click on the map to position and resize the scale bar. You will notice that you also have many options to choose from in changing its appearance using the Item properties tab on the right.

### Adding a legend

To add a legend, select <kbd>Layout &rarr; Add Legend</kbd> and use the mouse to draw a rectangle where you want the legend to appear. The legend will be automatically filled with the information in your layers list, but you can modify this using the Item properties tab on the right. Select the legend you have added and scroll down the Item properties to the <kbd>Legend Items</kbd> section. Uncheck <kbd>Auto update</kbd>. Now select the layers you do not wish to see in the legend and click the minus sign at the bottom to remove them. Next click the item(s) that you want in the legend and use the editing button to edit the text that will appear. In the <kbd>Main properties</kbd> section you can also change the title and alignment of the legend text.

### Exporting your map

When you are happy with your map, use <kbd>Composer &rarr; Export as Image...</kbd> or <kbd>Composer &rarr; Export as PDF...</kbd> to export your map to a single file, which you can then share, embed in a report, or print.

