# (PART) Spatial Analysis With Stata {-} 

# Getting Started with Stata

There are a number of ways to use Stata, and your choice will affect the overall workflow of your analysis. These include using the menus, typing commands directly in the console, and using do-files.

## Menus

The most intuitive approach for new users is to use the menus. Stata's comprehensive and well-organized menus are one of the features that makes it attractive, and you can learn a lot about what Stata has to offer simply by exploring the menus options. One drawback to using the menus, though, is that this makes it cumbersome to repeat steps from your work -- something that you often need to do in statistical analysis, and that you should always aim to make possible for others to do so that your work is replicable. Stata has a feature that can help with this, which is the option to create a log file that records everything you have done. This is something you should always do, even if working with the menus, as it allows you to go back and figure out exactly what you did, identify errors, etc. But going through a log file and repeating the commands can be tedious if you need to repeat your work multiple times. It is possible to create a "command log," which contains only the commands you typed and thus can be more easily repeated, but these repetitions will require that you move away from the menu approach in any case.

## Commands

An alternative to the menus is to type commands directly in the command console at the bottom. If you are using Stata in interactive mode (for instance on a server without a GUI), this is often the only possibility, as there will be no menus. This can save time when you start to learn the commands. It is also good for quick analysis that you do not intend to repeat. And you can still log your work, just as with the menus. Ultimately, though, for most analysis you will want to keep track of your work in a more systematic way, and this is where do-files come in.

## Do-Files

Do-Files are simply text files in which you store the commands you want to execute (also called a script). The key is that you can get Stata to execute these commends directly from the file. This can be done by selecting a line or set of lines and pressing _Ctrl-D_. (You can also press _Ctrl+D_ without anything selected in order to execute all lines, or you can press _Ctrl+Shift+D_ to execute all lines from wherever your cursor is to the bottom. If you forget this or want to see more options, just look at the _Tools_ menu in the do-file editor.) The most efficient way to work with Stata is to use a do-file and to also log your work. This way, you end up with a do-file that you can re-run (and modify) whenever you need to repeat your work, along with an exact log of what lines you ran and Stata's output. While working, you may skip around your do-file and run particular lines, but the goal is to produce a file that can be run from start to finish to accomplish your analysis. You can then give this to someone else and they should be able to use it to replicate what you have done (and check for errors).

There are certain useful pieces of information and commands that you should include at the beginning and end of any do-file. These include information about what the file is intended to do, who wrote it, what version of Stata is was written with, and the commands to start logging to the log file and then (at the end) to stop logging. The Stata version is particularly useful because as new versions of Stata are released, they all are all written to be compatible with older ones and to be able to run older do-files exactly as they were intended. Thus, if you write a do-file using Stata 13 and specify this in your do-file, you can insure that all future versions of Stata will run it using Stata 13 (and thus continue to exactly replicate your work). Here is an example:

```
// Spatial analysis of Chicago Crime data
// John Palmer - Spring 2019

version 15
clear
capture log close
log using chicago_analysis, text replace

// Here you would start your analysis for example:
display 2+2

log close
```



